### ISSUE TITLE
Support for python 3.8 (!?)

### ISSUE THREAD

**Issue by epsilon-0** [gvalkov/python-evdev#126]
I managed to get this to compile on python 3.8 and am wondering if it has any official testing or support for the new version of python.

Thanks a lot for making this.

**Comment by LinusCDE** [comment]
According to [this response](https://github.com/gvalkov/python-evdev/issues/65#issuecomment-416320511) in some other issue, the author likes to keep compatibility up with python 2.7 which I can understand since it's a fairly major library that will probably still get used by people who didn't migrate.

That answer I now two years old though and Python 2.7 is officially marked as dead for some months.

Either way there are still good reasons for and against python 3 inclusive support..
