### ISSUE TITLE
using tests in python-evdev

### ISSUE THREAD

**Issue by epsilon-0** [gvalkov/python-evdev#127]
Am wondering if the tests are still supported given that they are a fair bit old.

Just wanted to confirm if it is a good idea to enable them when packaging this up for gentoo :smile_cat:

**Comment by gvalkov** [comment]
Sorry for the late reply. Basically I never found a good way to test the core functionality of python-evdev (I should probably look at what libinput is doing ...). Still, running the tests is good for a quick sanity check (maybe exclude the uinput tests though, since they require `/dev/uinput` to be rw).
