### ISSUE TITLE
Is this repository maintained? 

### ISSUE THREAD

**Issue by PyDever** [gvalkov/python-evdev#96]
Is this repository maintained anymore? I see there are several issues. I am more than happy to takeover if owner doesn't have the time.

**Comment by gvalkov** [comment]
Hi @PyDever. I'm still maintaining the project though there is not much happening these days. Python-evdev is feature complete in my opinion (with some exceptions in uinput and force feedback event handling). 

The currently open issues are there mostly because:

1) Fixing them is not in scope of the project (i.e. keycode/scancode mapping).
2) Cross-compilation/installation on different embedded Linux distributions (e.g. openwrt) is hard and people need to know what they're doing.
3) The issue has been discussed, but never closed either by me or the reporter.
